security:
  oauth2:
    client:
      client-id: rrong1
      client-secret: rrongSecret1
#      当你请求需要身份认证的时候，把用户跳转到认证服务器上跳转过去的地址，（请求授权）
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
    resource:
      jwt:
#        带上clientId和clientSecret去请求 签名
        key-uri: http://127.0.0.1:9999/server/oauth/token_key

server:
  port: 8080
  context-path: /client1